package org.acp.client;

public enum FailReason {
    UNSUPPORTED_VERSION,
    UNSUPPORTED_CRYPTO_SUITE,
    UNSUPPORTED_MESSAGE_CLASS,
    INVALID_SIGNATURE,
    EXPIRED_MESSAGE,
    POLICY_REJECTED,
    PAYLOAD_TOO_LARGE,
    UNSUPPORTED_PROFILE
}
