spring:
  application:
    name: Dealer [Java]

poker:
  dealer:
    display-name: ${POKER_DEALER_DISPLAY_NAME:Dealer [Java]}
    player-ids:
      - "Player 1 [Go]"
      - "Player 2 [Python]"
      - "Player 3 [Rust]"
      - "Player 4 [TypeScript]"
    player-ucw:
      "Player 1 [Go]":
        participant-urn: ${POKER_PLAYER1_PARTICIPANT_URN:urn:co-operator:entity:000001}
      "Player 2 [Python]":
        participant-urn: ${POKER_PLAYER2_PARTICIPANT_URN:urn:co-operator:entity:000002}
      "Player 3 [Rust]":
        participant-urn: ${POKER_PLAYER3_PARTICIPANT_URN:urn:co-operator:entity:000003}
      "Player 4 [TypeScript]":
        participant-urn: ${POKER_PLAYER4_PARTICIPANT_URN:urn:co-operator:entity:000004}
    player-agent-ids:
      "Player 1 [Go]": ${POKER_PLAYER1_AGENT_ID:agent:player1@player1:8091}
      "Player 2 [Python]": ${POKER_PLAYER2_AGENT_ID:agent:player2@player2:8092}
      "Player 3 [Rust]": ${POKER_PLAYER3_AGENT_ID:agent:player3@player3:8093}
      "Player 4 [TypeScript]": ${POKER_PLAYER4_AGENT_ID:agent:player4@player4:8094}
    player-endpoints:
      "Player 1 [Go]": ${POKER_PLAYER1_ENDPOINT:http://player1:8091}
      "Player 2 [Python]": ${POKER_PLAYER2_ENDPOINT:http://player2:8092}
      "Player 3 [Rust]": ${POKER_PLAYER3_ENDPOINT:http://player3:8093}
      "Player 4 [TypeScript]": ${POKER_PLAYER4_ENDPOINT:http://player4:8094}
